name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. 檢查程式碼
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. 安裝 Bun（用官方 script 安裝）
      - name: Install Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          echo "$HOME/.bun/bin" >> $GITHUB_PATH

      # 3. 印出版本資訊確認 Bun 安裝成功
      - name: Check Bun version
        run: bun --version

      # 4. 安裝套件
      - name: Install dependencies
        run: |
          bun install

      # 5. 運行測試
      - name: Run tests
        run: |
          bun run test   # 使用 bun 執行測試

      # 6. 如果測試通過，build 出項目
      - name: Build Next.js
        run: |
          bun run build

      # 7. 部署到 Vercel
      - name: Deploy to Vercel
        if: success() # 只有在測試和 build 成功後才會執行
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: "--prod --yes"
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
